List<String> interestsName = [
  "Music",
  "Art",
  "Beauty",
  "Drawings",
  "Fitness",
  "Photography",
  "Fashion",
  "Animal",
  "Flower",
  "Food & Drink",
  "Quotes",
  "Interior Design",
  "Books",
  "Makeup",
  "Graphic Design",
  "Anime",
];

List<String> interestsImage = [
  "assets/images/interests/music.jpg",
  "assets/images/interests/art.jpg",
  "assets/images/interests/beauty.jpg",
  "assets/images/interests/drawings.jpg",
  "assets/images/interests/fitness.jpg",
  "assets/images/interests/phoyography.jpg",
  "assets/images/interests/fashion.jpg",
  "assets/images/interests/animal.jpg",
  "assets/images/interests/flower.jpg",
  "assets/images/interests/food_drink.jpg",
  "assets/images/interests/quotes.jpg",
  "assets/images/interests/interior_design.jpg",
  "assets/images/interests/books.jpg",
  "assets/images/interests/makeup.jpg",
  "assets/images/interests/graphic_design.jpg",
  "assets/images/interests/anime.jpg",
];
